
# GET a specific product
GET http://localhost:9090/store/demo-controller HTTP/1.1

###

POST http://localhost:9090/register HTTP/1.1
Content-Type: application/json

{
  "email":"user6@email.com",
  "password":"hehe",
  "firstname":"User",
  "lastname":"LastUser",
  "phoneNumber":"0123456789"
}
###

POST http://localhost:9090/store/authenticate HTTP/1.1
Content-Type: application/json

{
  "email":"george@gmail.com",
  "password":"parola123"
}

###
GET http://localhost:9090/products/keyboards HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyNkBlbWFpbC5jb20iLCJpYXQiOjE2ODY1ODY2MTYsImV4cCI6MTY4NjU4ODA1Nn0.pV9nq2im6SoMliCAbhE3zdT40YBzIZyspY9q4jGFJv8

###

POST http://localhost:9090/store/refresh-token HTTP/1.1
Authorization:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZEBhZC5jb20iLCJpYXQiOjE2ODY4MjMxMTQsImV4cCI6MTY4NzQyNzkxNH0.QQDrU-8p-nj-DK43PKc2O-GmKETFDUxl_EsqbJICPz0
